baseURL = 'https://brzgw555.github.io'
title = 'Zero'

# multi-language support
defaultContentLanguage = 'en'

# enable git info
enableGitInfo = true

# disable taxonomy, term and RSS (which removes categories, tags and index.xml)
disableKinds = ["taxonomy", "term", "RSS"]

[module]
  [[module.imports]]
    path = 'github.com/geekifan/zero-academic-page'

[languages]
  [languages.en]
    languageName = 'English'
    weight = 1
    title = 'Zero'

    [languages.en.params]
      author = "Xinzhe Wu"
      description = "An undergraduate in [Peking University](https://pku.edu.com),[zhi-class.ai](https://zhi-class.ai/zh-cn/)."
      motto = "Go bold to mess up , go eager to err."
    
    [[languages.en.menu.main]]
      name = 'About Me'
      url = '#about-me'
      weight = 1
    [[languages.en.menu.main]]
      name = 'News'
      url = '#news'
      weight = 2
    [[languages.en.menu.main]]
      name = 'Publications'
      url = '#publications'
      weight = 3
    [[languages.en.menu.main]]
      name = 'Honors and Awards'
      url = '#honors-and-awards'
      weight = 4
    [[languages.en.menu.main]]
      name = 'Educations'
      url = '#educations'
      weight = 5
      
[params]
  profilePicture = "images/firefly.jpg"
  enableDarkMode = true
  
  [[params.social]]
    name = "github"
    url = "https://github.com/brzgw555"
    icon = "fab fa-fw fa-github"
  [[params.social]]
    name = "email"
    url = "mailto:2400013093@stu.pku.edu.cn"
    icon = "fas fa-envelope"



[build]
  writeStats = false

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
